artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Rahul786Patidar/Text-Summarizer-Project/raw/main/summarizer-data.zip
  local_date_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion